name: gitleaks

on:
  push:
    branches: ["master","preparation"]
  pull_request:
    branches: ["master","preparation"]
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: FetchSourceCode
        uses: actions/checkout@v3
      - name: SecretScan
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
      - name: Upload
        uses: github/codeql-action/upload-sarif@v2
        if: always()
