name: syft

on:
  push:
    branches: ["master","preparation"]
  pull_request:
    branches: ["master","preparation"]
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: install syft
      run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest
    - name: Scan the image and upload dependency results
      run: syft localbuild/testimage:latest --scope all-layers -o sarif -t syft.sarif
    - name: Upload
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: syft.sarif
      if: always()
