name: Syft Scan

on:
  push:
    branches: ["master","preparation"]
  pull_request:
    branches: ["master","preparation"]
  workflow_dispatch:

jobs:
  syft-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Syft
      run: |
        wget https://github.com/anchore/syft/releases/download/v0.10.2/syft-cli-linux
        chmod +x syft-cli-linux
        sudo mv syft-cli-linux /usr/local/bin/syft
      # Use a Syft release suitable for your platform. You can find the latest releases at https://github.com/anchore/syft/releases.

    - name: Syft Scan
      run: |
        syft packages image:/path/to/your/container-image:tag --output sarif > syft-results.sarif
      # Replace "/path/to/your/container-image:tag" with the path to your container image.

    - name: Upload
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: syft-results.sarif
      if: always()
