name: syft

on:
  push:
    branches: ["master","preparation"]
  pull_request:
    branches: ["master","preparation"]
  workflow_dispatch:

jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: install syft
      run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest
    - name: Scan the image and upload dependency results
      run: syft localbuild/testimage:latest --scope all-layers -o json=syft.json -t .
    - name: convert
      run: |
        cat syft.json | jq '{version: "2.1.0", runs: [{tool: {driver: {name: "MyTool", version: "1.0.0"}}, results: [(.issues[] | {ruleId: .type, message: .description, level: .severity})]}]}' > syft.sarif
        echo "JSON to SARIF conversion complete."
        cat syft.sarif
    - name: Upload
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: syft.sarif
      if: always()
