name: trivy
on:
  push:
    branches: ["master","preparation"]
  pull_request:
    branches: ["master","preparation"]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: FetchSourceCode
        uses: actions/checkout@v3
      - name: BuildImage
        run: |
          docker build -t dockerimage .
      - name: Trivy
        run: brew install trivy;
             trivy dockerimage --format sarif -o report.sarif  golang:1.12-alpine
      - name: Upload
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: report.sarif
        if: always()
          
