name: trivy
on:
  push:
    branches: ["master","preparation"]
  pull_request:
    branches: ["master","preparation"]
  workflow_dispatch:
jobs:
  trivy:
    name: trivy
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Source Code
        uses: actions/checkout@v3

      - name: Build Image
        run: |
          docker build -t dockerimage .

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'dockerimage'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
        if: always()
