name: trivy
on:
  push:
    branches: ["master","preparation"]
  pull_request:
    branches: ["master","preparation"]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: FetchSourceCode
        uses: actions/checkout@v3
      - name: BuildImage
        run: |
          docker build -t dockerimage .
      - name: Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'dockerImage'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          
